// REGISTER
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

// LOGIN
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';


// Fetch user Profile

export const FETCH_PROFILE_REQUEST = 'FETCH_PROFILE_REQUEST'
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS'
export const FETCH_PROFILE_FAILURE = 'FETCH_PROFILE_FAILURE'


// FETCH JOB DATA
export const FETCH_JOB_REQUEST = 'FETCH_JOB_REQUEST'
export const FETCH_JOB_SUCCESS = 'FETCH_JOB_SUCCESS'
export const FETCH_JOB_FAILURE = 'FETCH_JOB_FAILURE'

// Search
export const SEARCH = 'SEARCH'

// Filtered Job

export const FILTERED_JOB = 'FILTERED_JOB'

// Job Suggestion

export const JOB_SUGGESTION_REQUEST = 'JOB_SUGGESTION_REQUEST'
export const JOB_SUGGESTION_SUCCESS = 'JOB_SUGGESTION_SUCCESS'
export const JOB_SUGGESTION_FAILURE = 'JOB_SUGGESTION_FAILURE'